image:
  tag: latest
build:
  enabled: true
  mode: s2i
  bootableJar:
    builderImage: registry.access.redhat.com/ubi8/openjdk-11:latest
    # Not yet released
    runtimeImage: registry-proxy.engineering.redhat.com/rh-osbs/ubi8-openjdk-11-runtime:1.12-1
  s2i:
    builderImage: quay.io/wildfly/wildfly-s2i-jdk11:latest
    runtimeImage: quay.io/wildfly/wildfly-runtime-jdk11:latest
  output:
    kind: "ImageStreamTag"
  triggers: {}
deploy:
  enabled: true
  replicas: 1
  route:
    enabled: true
    tls:
      enabled: true
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
  livenessProbe:
    httpGet:
      path: /health/live
      port: admin
  readinessProbe:
    httpGet:
      path: /health/ready
      port: admin
  startupProbe:
    httpGet:
      path: /health/live
      port: admin
    initialDelaySeconds: 5
    failureThreshold: 36
    periodSeconds: 5